---
title: "gapminder-dplyr"
author: "Robert Mason"
date: "19/06/2019"
output: html_document
---
Loading tidyverse
```{r}
library(tidyverse)
```

Load data
```{r}
#loading the gapminder dataset from github
gapminder<-read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")
head(gapminder)
tail(gapminder)

#str stands for structure
str(gapminder)

#column names of gapminder
names(gapminder)
ncol(gapminder)

```

Look at individual dataframe variables
```{r}
#show me the life Expectancy column
gapminder$lifeExp
```

Learning the filter() function

```{r}
filter(gapminder, lifeExp <29)
#just look at mexico
filter(gapminder, country =="Mexico")
```

```{r}
data1<-filter(gapminder,country=="Brazil",year < 2008)
data2<-filter(data1, year >1986)
mean(data2$lifeExp)

#another way:
filter(gapminder, country=="Brazil", year <2008, year>1986)
```

Learning the select function
```{r}
#These two lines do the same thing
select(gapminder, year, country, lifeExp)
select(gapminder, -continent,-gdpPercap,-pop)
```

Using 'filter()' and 'select()'
```{r}
gap_cambodia<-filter(gapminder, country="Cambodia")
gap_cambodia2<-select(gap_cambodia,-continent, -lifeExp)
```

Using the pipe '%>%'
ctrl + shift + m
pipes are much easier to decode
```{r pipe}
gapminder%>%head()
#is the same as 
head(gapminder)
#so
gap_cambodia<-filter(gapminder, country="Cambodia")
gap_cambodia2<-select(gap_cambodia,-continent, -lifeExp)
#becomes
gap_cambodia<-filter(gapminder, country="Cambodia")%<%select(-continent, -lifeExp)
#or even
gap_cambodia<-gapminder%<% filter(country=="Cambodia")%<%select(-continent,-lifeExp)

```

Learn 'mutate' which adds a new column
```{r}
#encourage you to keep each function on a new line when piping
gapminder%>%
  mutate(gdp = pop*gdpPercap)
```

```{r}
popasia<-gapminder%>%filter(continent=="Asia", year==2007)%>%mutate(pop_thousands = pop/1000)%>%select(country,year,pop_thousands)

```

Learning the 'group_by' function
```{r}
gapminder%>%
  filter(year == 2002)%>%
  group_by(continent)%>%
  mutate(cont_pop = sum(pop))
```

Add in 'summarise'
```{r}
gapminder%>%
  filter(year == 2002)%>%
  group_by(continent)%>%
  summarize(cont_pop = sum(pop))

```


```{r}
gapminder%>%
  group_by(continent,year)%>%
  summarize(cont_pop=sum(pop))%>%
  arrange(-year)%>%
  ungroup() #get into habitat of putting  ungroup at the end of a group operation
#Won't make a difference for summarizing but will make a difference for mutate.

```

```{r}
gapminder%>%
  mutate(gdp = pop * gdpPercap) %>%
  group_by(continent)%>%
  summarize(gdp_max=max(gdp))%>%
  filter(gdp == gdp_max)
```

